var annotated_dup =
[
    [ "dummyFktCallStruc", "structdummy_fkt_call_struc.html", null ],
    [ "evtQueue", "structevt_queue.html", "structevt_queue" ],
    [ "evtStruc", "structevt_struc.html", "structevt_struc" ],
    [ "gStruc_OS_FLAGS", "structg_struc___o_s___f_l_a_g_s.html", "structg_struc___o_s___f_l_a_g_s" ],
    [ "memBlckhead", "structmem_blckhead.html", "structmem_blckhead" ],
    [ "memMngrHead", "structmem_mngr_head.html", "structmem_mngr_head" ],
    [ "mqData", "structmq_data.html", "structmq_data" ],
    [ "mqDummyElmnt", "structmq_dummy_elmnt.html", "structmq_dummy_elmnt" ],
    [ "mqPrtcpnt", "structmq_prtcpnt.html", "structmq_prtcpnt" ],
    [ "mqPub", "structmq_pub.html", "structmq_pub" ],
    [ "mqSub", "structmq_sub.html", "structmq_sub" ],
    [ "mqSysSub", "structmq_sys_sub.html", "structmq_sys_sub" ],
    [ "mqTskSub", "structmq_tsk_sub.html", "structmq_tsk_sub" ],
    [ "msgFktCallStruc", "structmsg_fkt_call_struc.html", "structmsg_fkt_call_struc" ],
    [ "msgPrvdrsUnion", "unionmsg_prvdrs_union.html", "unionmsg_prvdrs_union" ],
    [ "msgQ", "structmsg_q.html", "structmsg_q" ],
    [ "msgQMsgProvStruc", "structmsg_q_msg_prov_struc.html", "structmsg_q_msg_prov_struc" ],
    [ "partID", "unionpart_i_d.html", "unionpart_i_d" ],
    [ "semStruc", "structsem_struc.html", "structsem_struc" ],
    [ "syncEleStruc", "structsync_ele_struc.html", "structsync_ele_struc" ],
    [ "sysFkt", "structsys_fkt.html", "structsys_fkt" ],
    [ "sysMsgProvStruc", "structsys_msg_prov_struc.html", "structsys_msg_prov_struc" ],
    [ "sysTckFktCallstruc", "structsys_tck_fkt_callstruc.html", "structsys_tck_fkt_callstruc" ],
    [ "sysTickEleIDUnion", "unionsys_tick_ele_i_d_union.html", null ],
    [ "sysTickTMRStruc", "structsys_tick_t_m_r_struc.html", "structsys_tick_t_m_r_struc" ],
    [ "sysTimerStruc", "structsys_timer_struc.html", "structsys_timer_struc" ],
    [ "timerStruc", "structtimer_struc.html", "structtimer_struc" ],
    [ "tmrFktCallStruc", "structtmr_fkt_call_struc.html", "structtmr_fkt_call_struc" ],
    [ "tskMailBox", "structtsk_mail_box.html", "structtsk_mail_box" ],
    [ "tskMsgProvStruc", "structtsk_msg_prov_struc.html", "structtsk_msg_prov_struc" ],
    [ "tskPrioArEle", "structtsk_prio_ar_ele.html", "structtsk_prio_ar_ele" ],
    [ "tskTCB", "structtsk_t_c_b.html", "structtsk_t_c_b" ],
    [ "tskTimerStruc", "structtsk_timer_struc.html", "structtsk_timer_struc" ]
];